<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Anggota_model extends CI_Model
{

    public $table = 'permohonan_butir_peribadi';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_penuh', $q);
	$this->db->or_like('no_mykad', $q);
	$this->db->or_like('tarikh_lahir', $q);
	$this->db->or_like('kewarganegaraan', $q);
	$this->db->or_like('umur', $q);
	$this->db->or_like('no_telefon', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('poskod', $q);
	$this->db->or_like('emel', $q);
	$this->db->or_like('bangsa', $q);
	$this->db->or_like('etnik', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('taraf_perkahwinan', $q);
	$this->db->or_like('kategori_kelulusan', $q);
	$this->db->or_like('kelulusan', $q);
	$this->db->or_like('matlamat', $q);
	$this->db->or_like('kategori_pemohon', $q);
	$this->db->or_like('no_rujukan_permohonan', $q);
	$this->db->or_like('pengesahan', $q);
	$this->db->or_like('pengakuan', $q);
	$this->db->or_like('tarikh_hantar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama_penuh', $q);
	$this->db->or_like('no_mykad', $q);
	$this->db->or_like('tarikh_lahir', $q);
	$this->db->or_like('kewarganegaraan', $q);
	$this->db->or_like('umur', $q);
	$this->db->or_like('no_telefon', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('poskod', $q);
	$this->db->or_like('emel', $q);
	$this->db->or_like('bangsa', $q);
	$this->db->or_like('etnik', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('taraf_perkahwinan', $q);
	$this->db->or_like('kategori_kelulusan', $q);
	$this->db->or_like('kelulusan', $q);
	$this->db->or_like('matlamat', $q);
	$this->db->or_like('kategori_pemohon', $q);
	$this->db->or_like('no_rujukan_permohonan', $q);
	$this->db->or_like('pengesahan', $q);
	$this->db->or_like('pengakuan', $q);
	$this->db->or_like('tarikh_hantar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Anggota_model.php */
/* Location: ./application/models/Anggota_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-21 13:37:40 */
/* http://harviacode.com */